### ISSUE TITLE
no clear way to set the host=sandbox.finapi.io

### ISSUE THREAD

**Issue by faridos** [chbndrhnns/finapi-client#1]
hello :)
i am intrested in your repository and trying to test it but i can not find a way to set the Configuration host, and it is not mentionned in the docs, can you point us to the way to do it ?
it is right now localhost for all apis, but i would like have te possiblity to change it for all or for some apis ,

**Comment by chbndrhnns** [comment]
You are right, the host is hard-coded in the code. The whole project has been auto-generated using the `swagger-codegen` framework and I do not intend to maintain it in some way.
You could set the `host` field in the configuration class for a quick win but I would assume that the API has evolved over the last three years.

I recommend using the [official docs](https://docs.finapi.io/) as a starting point.

**Comment by faridos** [comment]
Hey, i tried but no success. Does not accept configuration.host= blabla
Or
Configuration(host=blabla)
Thanx anyway.i will try more

**Comment by chbndrhnns** [comment]
I suggested to change the host directly in the Python file, not passing it to the constructor.
